### ISSUE TITLE
Local Peer-to-Peer API

### ISSUE THREAD

**Issue by ibelem** [ibelem/local-peer-to-peer#7]
## Introduction

The Local Peer-to-Peer API enables mobile and desktop devices to transfer messages or files directly between devices through close-range communication in a privacy-preserving manner. As of today, these tasks on the web require the use of a centralized cloud service, a WebRTC-based solution or an email service that all transfer data through the internet.

![problem](https://raw.githubusercontent.com/ibelem/local-peer-to-peer/main/images/problem.svg)

When a user wants to transfer messages or files to another device nearby none of the existing solutions provide a compelling user experience because web applications are not privy to local communication technologies optimized for these tasks. This proposal solves this problem by enabling web applications to use applicable local communication technologies for data transfer between devices. This improve user experience, enhances user’s privacy and works offline without internet connectivity as is expected of every modern web application.

[Read the complete Explainer](https://github.com/ibelem/local-peer-to-peer/blob/main/EXPLAINER.md)

## Feedback

I welcome feedback in this thread, but encourage you to file bugs against [the Explainer](https://github.com/ibelem/local-peer-to-peer/blob/main/EXPLAINER.md)

[explainer]: http://domain.tld/your/explainer.md "Explainer Title"

**Comment by anssiko** [comment]
(@ibelem, this issue that was used as a staging area for refining the WICG issue submission, feel free to close.)

**Comment by ibelem** [comment]
Thanks for the reminder @anssiko, close this issue. There will be lively discussions in the community and upcoming events, thank you @anssiko!
